version: '3.8'
services:
    database:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-symfony}
            - MYSQL_USER=${MYSQL_USER:-symfony}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-symfony}
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
volumes:
    database:

